@server = https://ernestooopc-glorious-eureka-xjg6w6q74wrc97j-8080.app.github.dev
###
GET {{server}}/api/ciudades

###
GET {{server}}/api/personas

###

POST {{server}}/api/ciudades
Content-Type: application/json

{"nombre": "VMT", "codigoPostal": "16545", "region": "Lima"}


###
GET {{server}}/api/departamentos

###
GET {{server}}/api/departamentos/1/formacion


###
GET {{server}}/api/ciudadanos
